### ISSUE TITLE
prefix for ionicon not predictable/ not working?

### ISSUE THREAD

**Issue by dcossyleon** [rstudio4edu/rstudio4edu-book#27]
* Using the logo-name as supplied on the ionicon's website does not render the appropriate icon in rmd

The twitter icon will show up in rmd only when "ion-social-twitter" is used (this is the only ionicon example given in the R Markdown book), but the name of the icon on iconicon's website is "logo-twitter". It's not clear how anyone would know to use social as part of the prefix.

![image](https://user-images.githubusercontent.com/29008894/61164859-4c89a300-a4e7-11e9-9fff-e96163b512d7.png)

* As another example,  it's not clear how to figure out how to use the icon for "school". It will not render, even after trying the following:

- ion-icon-school
- ion-school

![image](https://user-images.githubusercontent.com/29008894/61164813-a342ad00-a4e6-11e9-8a1f-0b4035c3835f.png)

**Comment by dcossyleon** [comment]
Actually, running into issues with some (free) font awesome icons also (e.g. `fa-carrot`, `fa-pizza`). Is there only a subset of font awesome icons that work with rmd?

**Comment by apreshill** [comment]
I've run into the same thing- I wonder if you could ask on community.rstudio.com?

**Comment by dcossyleon** [comment]
- ionicon v2 icons available with RMD: https://ionicons.com/v2/cheatsheet.html
- font awesome icons released after v5.1.0 are not available for RMD. I couldn't find a cheatsheet with only icons from versions ≤ 5.1.0, but at least you can see whether the icon you're trying to use has too new of a version (e.g. as it does with carrot):

![image](https://user-images.githubusercontent.com/29008894/62217533-cbe8f480-b378-11e9-9603-0867813fcce3.png)

**Comment by dcossyleon** [comment]
font awesome icons for `bookdown` only go up to v4.7

https://github.com/rstudio/bookdown/pull/464

**Comment by dcossyleon** [comment]
Blergh-- spoke too soon. This does the exact same thing as the `icon` package.
