### ISSUE TITLE
make new kinds of tip divs

### ISSUE THREAD

**Issue by dcossyleon** [rstudio4edu/rstudio4edu-book#29]
- Gotchas/ Watchouts
- tip: maybe these should be advice bits that are action-oriented. 
- FYI: more background info
- workflow div: e.g. now push to github, etc. (or perhaps should be an rstudio tip)

**Comment by apreshill** [comment]
Now that I'm using bookdown for prepping a workshop, I wonder if we could make 2 more divs that we may or may not actively use in this book, but probably want to show people "how to":

1. Your turns (when you want to cue the reader to actually do something on their machine vs passively reading)

1. Live coding (when you want to insert sort of a "pause" for readers to note when you demo'ed live code in a workshop or a class)

**Comment by dcossyleon** [comment]
What do you think about these @apreshill? I was thinking it might be better to have them be more neutral-looking than the one I had previously so that they match a wider variety of bookdowns

__Live code:__
![Live-code](https://user-images.githubusercontent.com/29008894/61843301-c5321d00-ae60-11e9-8e83-d2ccd7775671.png)

__fyi:__
![fyi](https://user-images.githubusercontent.com/29008894/61843302-c5cab380-ae60-11e9-816b-4d0099198f3d.png)

__gotcha:__
![Gotcha](https://user-images.githubusercontent.com/29008894/61843303-c5cab380-ae60-11e9-85bd-e0cfd1e4b8c0.png)

__your turn:__
![Your-turn](https://user-images.githubusercontent.com/29008894/61843304-c5cab380-ae60-11e9-817e-cfde19fe0f1c.png)

__generic tip:__
![Lightbulb](https://user-images.githubusercontent.com/29008894/61843305-c5cab380-ae60-11e9-808c-c7265cc5a04c.png)

workflow (rstudio tip) could be a faucet, perhaps?

**Comment by dcossyleon** [comment]
Added an illustrated cactus gotcha div tip for now with this commit: 4479e8b201c9a40dc458a120e3c0ac85d47396d6

Let's stick with 3 rstudio4edu div tips for now: 1) lightbult/note 2) rstudio-tip 3) gotcha

We can add a couple more if we feel we need to, once we've combed through the book
