### ISSUE TITLE
Add sidebar divs to bookdown book

### ISSUE THREAD

**Issue by apreshill** [rstudio4edu/rstudio4edu-book#3]
https://github.com/hadley/r-pkgs/blob/58dd635b423861382f2856742303833e27aef5a9/style.css#L16:L51

<img width="794" alt="Screen Shot 2019-06-18 at 12 36 19 PM" src="https://user-images.githubusercontent.com/12160301/59714101-b0a99780-91c5-11e9-9ea9-7cfb4c16dc2d.png">

Source code:

```
:::rstudio-tip
Through the book, we highlight specific ways that RStudio can expedite your package development workflow, in specially formatted sections like this.
:::
```

This will only work with bookdown b/c it is using pandoc.

**Comment by dcossyleon** [comment]
I've replaced the previous "notes"/ "alerts" with sidebar divs and tweaked the CSS. One for rstudio tips and another for just regular tips. I'm not completely happy with the current styling I've create for them, but I'll revisit it once higher priority issues are out of the way.
