### ISSUE TITLE
icon rending problem?

### ISSUE THREAD

**Issue by dcossyleon** [rstudio4edu/rstudio4edu-book#42]
After this  most recent merge ce21d27ed26c87de57749b3fa1b33cb3ab629feb, some icons are not rendering, like github and twitter share icons in the toolbar.

![image](https://user-images.githubusercontent.com/29008894/63066230-102ad780-bed7-11e9-981f-d110a464cc8f.png)

* The link to the github repo is also broken. This has been broken for a while, though, so it's unrelated to the icons not rendering. But I'm not sure why it's happening

**Comment by dcossyleon** [comment]
@apreshill - looks like the `icon` package is the culprit here. Uninstalling the package and building the book without restores our toolbar icons

Possibly related to this issue: https://github.com/ropenscilabs/icon/issues/25

**Comment by apreshill** [comment]
Ah I had this suspicion since that was the only package I added

**Comment by apreshill** [comment]
fixed with b232932603d5e46fc20829e0d2952b28890c16e8
